### ISSUE TITLE
Missing AMR genes in tsv table

### ISSUE THREAD

**Issue by tpillone** [arpcard/rgi#30] opened 2018-12-07 10:27 UTC
Hello,

I'm using "rgi tab" to convert the rgi json output to tsv, but I just observed that one gene ("Strict" hit present in the json) is  missing in the tsv file. I could also see it on the CARD website: https://card.mcmaster.ca/rgi/results/4syeT6jexACqyFwrq4yKeRm3kEpZf0L7bj5Iqxxy

In that example, the gene vanA is present in the wheel ..

![screenshot from 2018-12-07 11-07-58](https://user-images.githubusercontent.com/33416812/49641668-28298d80-fa11-11e8-97e7-ef8ea39c1d7d.png)

... but absent from the table

![screenshot from 2018-12-07 11-08-14](https://user-images.githubusercontent.com/33416812/49641679-2c55ab00-fa11-11e8-86ab-e3cf08debc70.png)

What could be the reason for this discrepancy?

Problematic json file: [rgi.zip](https://github.com/arpcard/rgi/files/2656804/rgi.zip)

**Comment by arpcard** [comment] 2018-12-07 16:09
Hi Trestan,


Thank you for your detailed email.


The issue is with picking the to hsp when creating the tab-delimited file.


In the json file there is two hsps, and VanA should be the top hit.


We will fix this.


Cheers,
Amos.


On Dec 7, 2018, at 5:27 AM, Trestan Pillonel <notifications@github.com> wrote:


Hello,
I'm using "rgi tab" to convert the rgi json output to tsv file, but I just observed that one gene ("Strict" hit present in the json) is missing in the tsv file. I could also see it on the CARD website:

https://card.mcmaster.ca/rgi/results/4syeT6jexACqyFwrq4yKeRm3kEpZf0L7bj5Iqxxy
In that example, the gene vanA is present in the wheel ..

... but absent from the table

What could be the reason for this discrepancy?
Problematic json file: 
rgi.zip
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by rmzelle** [comment] 2019-02-14 18:23
I have a very similar issue in that the contents of the “AMR Genes”, “AMR Gene Family”, and “Resistance Mechanism” tabs don't seem to match with that of the “Table View” tab. I just (re)analyzed my genome of interest today, and sorting the table on "% Identity of Matching Region" shows that no hit has an identity higher than 60%:

![image](https://user-images.githubusercontent.com/77951/52807906-b7c76a00-305a-11e9-98b6-de2918a96a44.png)

Meanwhile the other tabs show hits with much higher identities, e.g.:

![image](https://user-images.githubusercontent.com/77951/52808087-17257a00-305b-11e9-902d-f58e50046e23.png)

![image](https://user-images.githubusercontent.com/77951/52808236-62d82380-305b-11e9-8c83-7494a9c75729.png)

(I already reported this by email on 2019-02-12, but posting here as well)

**Comment by rmzelle** [comment] 2019-05-15 18:40
@tpillone, I no longer observe this discrepancy with the latest CARD 5.0.0/RGI 3.0.2. Could you rerun your sample to see if this has been resolved for you as well?

**Comment by raphenya** [comment] 2019-08-16 13:39
> @tpillone, I no longer observe this discrepancy with the latest CARD 5.0.0/RGI 3.0.2. Could you rerun your sample to see if this has been resolved for you as well?

@tpillone do you have any updates on this?

**Comment by tpillone** [comment] 2019-08-19 09:34
I no longer have this problem with rgi 5.0.0/card 3.0.3. 

Be careful if you install rgi 5.0.0 with conda or if you have biopython 1.74 installed, there is a bug in the BLAST xml parser used by rgi (https://github.com/biopython/biopython/issues/2179).

**Comment by raphenya** [comment] 2019-08-20 12:43
> Be careful if you install rgi 5.0.0 with conda or if you have biopython 1.74 installed, there is a bug in the BLAST xml parser used by rgi (biopython/biopython#2179).

Yes, the fix will be included in biopython 1.75. For now, use biopython 1.72

**Closed by raphenya** 2019-08-20 12:43 UTC
