### ISSUE TITLE
protein have Similarity，but no reads could map to gene DNA

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/rgi#113] opened 2020-07-16 07:18 UTC
hi sir :
   i get a orf,  and the protein of orf could blast to marA protein.
  but there is no reads could be mapped to marA gene DNA sequence  with bwa or kma local aligment.
the orf seq as below:
ATGCAGAACGATAAAGATCTCTCCACGTGGCAGACCTTCCGCCGACTTTGGCCGATTATCGCGCCGTTTAAAGCCGGGCTAATCGTAGCGGCGGTGGCGTTGGTGCTTAACGCGGGCAGTGACACCTTCATGTTATCGCTTCTTAAACCGTTATTGGATGATGGTTTTGGTAAAACGGATCGCTCAGTGCTGCTATGGATGCCGCTGGTGGTTATCGGCCTGATGGTGCTGCGTGGGATCACCAGCTACATCTCGAGCTATTGTATTTCCTGGGTTTCCGGCAAAGTGGTGATGACCATGCGTCGTCGCCTGTTCGGCCACATGATGGGTATGCCGGTGGCCTTCTTTGACAAGCAGTCTACCGGAACGCTGCTGTCACGCATCACCTATGATTCTGAGCAGGTCGCCTCCTCTTCTTCCAGCGCGCTGATCACCGTGGTCCGCGAAGGAGCATCGATTATCGGTCTGTTCGTGATGATGTTCTATTACAGCTGGCAGCTGTCGCTGATCCTGATCGTACTGGCGCCGATTGTGTCGGTGGCGATCCGCGTGGTCTCCAAGCGTTTTCGCAATATCAGTAAGAATATGCAGAACACGATGGGGCAGGTCACCACCAGCGCCGAGCAGATGCTGAAAGGGCACAAAGAGGTGCTGATGTTTGGCGGCCAGGAAGTGGAAACCAAACGTTTTGATAAAGTCAGCAATAAAATGCGTCTGCAGGGGATGAAGATGGTTTCCGCCTCGTCTATCTCCGACCCGATCATTCAGCTTATCGCCTCCCTGGCGCTGGCCTTTGTCCTGTATGCCGCCAGCTTCCCGAGCGTGATGGACACCCTGACCGCCGGGACCATTACCGTGGTCTTCTCCTCGATGATTGCGCTGATGCGTCCGCTGAAGTCGCTGACCAACGTCAATGCCCAGTTCCAGCGCGGGATGGCGGCGTGCCAGACGCTGTTTGCGATCCTCGATTCCGAGCAGGAAAAAGACGAAGGTACGCGGGTCATTGAGCGGGCGAAAGGCAATCTCAAGTTCGAGAACGTCACCTTTACCTACCCGGGTCGCGAAGTGGCCGCGCTGCGCAATATCAATCTCGATATCCCGGAAGGGAAAACAGTGGCGCTGGTGGGGCGCTCAGGGTCGGGTAAATCGACCATTGCCAGCCTGATCACCCGCTTCTACGATGTCGACGAGGGGCAGATCCTGCTGGATGGCCACGACCTGCGCGAGTACAAGCTGAGCTCGCTGCGCGACCAGGTGGCGCTGGTTTCACAAAACGTGCATCTGTTCAACGATACCGTCGCCAACAATATCGCCTATGCCCGTACCGAAGAGTACAGCCGCGAGCAGATTGAAGAGGCCGCGCGCATGGCCTACGCCATGGATTTCATTAACAAGATGGATAATGGTCTGGATACCATCATCGGCGAGAATGGCGTGATGCTGTCCGGCGGCCAGCGCCAGCGTATTGCTATTGCCCGCGCGCTGCTGCGTAACAGCCCGATCCTGATCCTCGATGAAGCCACCTCGGCGCTGGATACCGAGTCCGAGCGTGCTATTCAGGCGGCGCTGGATGAGCTGCAGAAAAACCGTACCTCGCTGGTTATCGCTCACCGTCTGTCGACCATTGAGCAGGCTGATGAAATCGTGGTGGTTGAAGACGGGCGGATCGTGGAGCGCGGAACGCACCATGACCTGCTGGAGCATAAGGGCGTGTACGCCCAGCTGCATAAGATGCAATTCGGCGAATGA

**Comment by huynhw1** [comment] 2020-07-16 13:57
Hello @feihongloveworld ,

Have you made sure the match counts as a Strict or Perfect match? I am suspecting it's not being reported because RGI calls it a loose match.

All the best.

**Comment by raphenya** [comment] 2020-07-17 02:49
@feihongloveworld 

> i get a orf, and the protein of orf could blast to marA protein.

How did you get this? 

- Running BLAST on your provided sequence on ncbi matches `lipid A ABC transporter ATP-binding
                     protein/permease MsbA`
   - Top hit: https://www.ncbi.nlm.nih.gov/nucleotide/CP054780.1?report=genbank&log$=nuclalign&blast_rank=1&RID=H23JMA2K016&from=3568444&to=3570192

- Running your sequence using `rgi main` yields the following:
```
Cut_Off	Best_Hit_ARO	Best_Identities	Drug Class	Resistance Mechanism	AMR Gene Family
Strict	msbA	92.78	nitroimidazole antibiotic	antibiotic efflux	ATP-binding cassette (ABC) antibiotic efflux pump
``` 

> but there is no reads could be mapped to marA gene DNA sequence with bwa or kma local aligment.

Can you share how you did this?

Please, in the future use our template for submitting an issues which will help us reproduce.

**Comment by feihongloveworld** [comment] 2020-07-17 02:53
the reason is that ： DNA is Diversity , protein is conservative。

**Comment by raphenya** [comment] 2022-10-14 15:00
@feihongloveworld closing this issue. Please re-open if you need more help.

**Closed by raphenya** 2022-10-14 15:00 UTC
