### ISSUE TITLE
where can i find  the "wildcard_database_version.fasta" file? 

### ISSUE THREAD

**Issue by outbig** [arpcard/rgi#94] opened 2020-04-02 01:12 UTC
Dear, 

I am loading CARD db for metagenome analysis, but can't find a wildcard_db_VERSION.fasta file. I found that the the wildcard_data.tar.bz2 has now changed to the card-prevalence.tar.bz2. The db fasta files was not present in it. Looking forward to your answer. 

Best, 
Yongkyu

**Comment by LeonardosMageiros** [comment] 2020-04-03 10:59
I just had the same problem. 
I believe that the issue is in the previous step. 
The solution can be found here:
https://github.com/arpcard/rgi/issues/70#issuecomment-548803889

In short you have to extract the gz files with the wildcard directory first. 

Maybe it would be a good idea to update the instructions as this is indeed a bit confusing. 

Best 
Leo

**Comment by AroArz** [comment] 2020-04-08 08:54
This still doesnt really answer the question of what `-v version_number` your supposed to use.

e.g. `rgi wildcard_annotation -i wildcard --card_json /path/to/card.json -v version_number > wildcard_annotation.log 2>&1`

In their example they have `rgi load --wildcard_annotation wildcard_database_v3.0.2.fasta --wildcard_index /path/to/wildcard/index-for-model-sequences.txt --card_annotation card_database_v3.0.1.fasta` 

I assume it is supposed to be the same as the CARD database previously downloaded? I.e. `wildcard_database_v*.fasta` and `card_database_v*.fasta` should be the same?

**Comment by LeonardosMageiros** [comment] 2020-04-08 09:07
I just gave the same version as the card db previously downloaded. 
Just to be clear I am not in the development team but giving the same version there and running rgi on a few metagenomes worked for me. 

Best 
Leo

**Comment by AroArz** [comment] 2020-04-08 09:13
No I understand, just thought I'd mention it as well for the developers to see and provide clearer instructions.

**Comment by arpcard** [comment] 2020-05-11 14:47
Thank you for letting us know!

We will be sure to make it more clear which version number to use in the future.
I am assuming from the comments that the issue is resolved then.

I will be closing this issue.

**Closed by arpcard** 2020-05-11 14:47 UTC

**Comment by nickp60** [comment] 2022-07-29 19:42
This still has not been clarified in the readme.  If the versions of the wildcard database and the main database are always linked there should perhaps be a `VERSION=$(rgi database --version )` call to catch the version before making the wildcard file.
